name: Build Jekyll Site

on:
  push:
    branches:
      - task

env:
  JEKYLL_ENV: production
  AWS_REGION: us-east-1
  S3_BUCKET: bootstrapweb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        cd site
        bundle install
    - name: Build site
      run: |
        bundle exec jekyll build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_gh_pages

    - name: Create version file
      run: |
        echo "Job: ${GITHUB_JOB}\nBuild: ${GITHUB_RUN_NUMBER}" > ./_gh_pages/version.txt
    - name: Publish to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        args: _gh_pages
        bucket: ${{ env.S3_BUCKET }}
        region: ${{ env.AWS_REGION }}
        acl: public-read
        env_vars: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}